# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       ngfd

# >> macros
# << macros

Summary:    Non-graphic feedback service for sounds and other events
Version:    0.63
Release:    1
Group:      System/Daemons
License:    LGPL 2.1
URL:        https://meego.gitorious.org/maemo-multimedia/ngfd
Source0:    %{name}-%{version}.tar.gz
Source1:    ngfd.service
Source100:  ngfd.yaml
Requires:   %{name}-settings
Requires:   systemd-user-session-targets
BuildRequires:  pkgconfig(glib-2.0) >= 2.18.0
BuildRequires:  pkgconfig(dbus-1) >= 1.0.2
BuildRequires:  pkgconfig(dbus-glib-1)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(gstreamer-0.10)
BuildRequires:  pkgconfig(gstreamer-controller-0.10)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gobject-2.0)
BuildRequires:  pkgconfig(gthread-2.0)
BuildRequires:  pkgconfig(check)
BuildRequires:  pkgconfig(mce)
BuildRequires:  pkgconfig(profile)
BuildRequires:  doxygen

%description
This package contains the daemon servicing the non-graphical feedback
requests.


%package plugin-devel
Summary:    Development package for ngfd plugin creation
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description plugin-devel
This package contains header files for creating plugins to non-graphical feedback daemon.

%package plugin-fake
Summary:    Fake plugins for ngfd testing
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description plugin-fake
Fake plugins for ngfd testing.

%package settings-basic
Summary:    Example settings for ngfd
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   %{name}-settings

%description settings-basic
Example settings for ngfd.

%package plugin-doc
Summary:    Documentation package for ngfd plugin creation
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description plugin-doc
This package contains documentation to header files for creating plugins to non-graphical feedback daemon.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%autogen --enable-debug
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
install -D -m 644 %{SOURCE1} %{buildroot}%{_libdir}/systemd/user/ngfd.service
mkdir -p %{buildroot}%{_libdir}/systemd/user/user-session.target.wants
ln -s ../ngfd.service %{buildroot}%{_libdir}/systemd/user/user-session.target.wants/
# << install post

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%config(noreplace) %{_sysconfdir}/dbus-1/system.d/%{name}.conf
%{_datadir}/dbus-1/services/com.nokia.NonGraphicFeedback1.Backend.service
%{_bindir}/%{name}
%{_libdir}/ngf/libngfd_dbus.so
%{_libdir}/ngf/libngfd_resource.so
%{_libdir}/ngf/libngfd_transform.so
%{_libdir}/ngf/libngfd_gst.so
%{_libdir}/ngf/libngfd_mce.so
%{_libdir}/ngf/libngfd_streamrestore.so
%{_libdir}/ngf/libngfd_tonegen.so
%{_libdir}/ngf/libngfd_callstate.so
%{_libdir}/ngf/libngfd_profile.so
%{_libdir}/ngf/libngfd_ffmemless.so
%{_libdir}/systemd/user/ngfd.service
%{_libdir}/systemd/user/user-session.target.wants/ngfd.service
# << files

%files plugin-devel
%defattr(-,root,root,-)
# >> files plugin-devel
%doc COPYING
%{_includedir}/ngf/*
%{_libdir}/pkgconfig/ngf-plugin.pc
# << files plugin-devel

%files plugin-fake
%defattr(-,root,root,-)
# >> files plugin-fake
%{_libdir}/ngf/libngfd_fake.so
%{_libdir}/ngf/libngfd_test_fake.so
# << files plugin-fake

%files settings-basic
%defattr(-,root,root,-)
# >> files settings-basic
%doc COPYING
%{_datadir}/ngfd/
# << files settings-basic

%files plugin-doc
%defattr(-,root,root,-)
%doc COPYING
%{_docdir}/ngfd-plugin/html/*
# >> files plugin-doc
# << files plugin-doc
